Repository AY2223S1-CS2103T-T17-3/tp, pull requests merged in 2022-10, with the labels that each got.

#92 Sort profiles list alphabetically
  src/main/java/seedu/address/model/profile/Name.java
  src/main/java/seedu/address/model/profile/Profile.java
  src/main/java/seedu/address/model/profile/UniqueProfileList.java
Labels: type.Enhancement, priority.Low

#88 Fix bug with date-only formats
  src/main/java/seedu/address/model/event/DateTime.java
  src/test/java/seedu/address/model/event/DateTimeTest.java
Labels: type.Bug, priority.Medium, severity.Low

#93 Add functionality for viewing upcoming events
  src/main/java/seedu/address/logic/commands/event/EventCommand.java
  src/main/java/seedu/address/logic/commands/event/ViewUpcomingEventsCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/event/EventCommandParser.java
  src/main/java/seedu/address/logic/parser/event/ViewUpcomingEventsCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/event/DateTime.java
  src/main/java/seedu/address/model/event/StartDateWithinTimeFramePredicate.java
  src/test/java/seedu/address/logic/commands/event/ViewUpcomingEventsCommandTest.java
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/address/logic/parser/event/ViewUpcomingEventsCommandParserTest.java
Labels: priority.High

#102 Add tag shortcuts functionality
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/tag/TagUtil.java
  src/test/java/seedu/address/model/tag/TagUtilTest.java
Labels: priority.High

#116 Update UI for v1.3
  src/main/java/seedu/address/model/event/DateTime.java
  src/main/java/seedu/address/ui/EventCard.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/dateTime_icon.png
  src/main/resources/images/duration_icon.png
  src/main/resources/view/EventListCard.fxml
  src/main/resources/view/EventListPanel.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ProfileListPanel.css
  src/main/resources/view/ProfileListPanel.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/Theme.css
  src/test/java/seedu/address/model/event/DateTimeTest.java
Labels: type.Enhancement, priority.Medium

#127 Encapsulate event operations in the model
  src/main/java/seedu/address/logic/commands/profile/DeleteProfileCommand.java
  src/main/java/seedu/address/logic/commands/profile/EditProfileCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/event/UniqueEventList.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/model/ModelStub.java
Labels: severity.VeryLow
